name: hs
version: 0.1.0.0
github: "githubuser/hs"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - template-haskell
  - time
  - QuickCheck
  - checkers
  - containers
  - parallel
  - bytestring
  - wreq # HB.Ch21
  - transformers
  - random
  - trifecta
  - raw-strings-qq
  - text
  - hspec
  - attoparsec
  - repa
  - vector

default-extensions:
  - TemplateHaskell

library:
  source-dirs: src

# ghc-options:
# - -Werror
# - -ddump-splices # Shows TemplateHaskell replacements

executables:
  hs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fasm
      - -O2
    dependencies:
      - hs
    extensions:
      - TemplateHaskell

  bench:
    main: Bench.hs
    other-modules: []
    source-dirs:
      - bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -fasm
      - -fforce-recomp
    dependencies:
      - hs
      - criterion
    extensions:
      - TemplateHaskell

  aoc2023:
    main: Main.hs
    other-modules:
      [
        Day01,
        Day02,
        Day03,
        Day04,
        Day05,
        Day06,
        Day07,
        Day08,
        Day09,
        Day10,
        Day11,
        Day12,
        Day13,
        Day14,
        Day15,
      ]
    source-dirs:
      - AoC2023
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fasm
      - -O2
    dependencies:
      - hs
      - parallel
    extensions:
      - TemplateHaskell

  mt:
    main: Main.hs
    other-modules: []
    source-dirs:
      - mt
    ghc-options:
      - -threaded
      - -O2
    dependencies:
      - hs
      - parallel

tests:
  hs-test:
    main: Test.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hs
      - tasty
      - tasty-smallcheck
      - tasty-quickcheck
      - tasty-hunit
    extensions:
      - TemplateHaskell
